# Generated by Django 5.2.16 on 2026-07-26.

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationSyncJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_id", models.CharField(db_index=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("deactivated_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CreatorContactTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="联系达人", max_length=160)),
                ("store_id", models.CharField(db_index=True, max_length=80)),
                (
                    "top_n",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("greeting_snapshot", models.TextField(max_length=2000)),
                (
                    "greeting_sha256",
                    models.CharField(editable=False, max_length=64),
                ),
                (
                    "invitation_name_snapshot",
                    models.CharField(max_length=255),
                ),
                (
                    "invitation_id_snapshot",
                    models.CharField(
                        help_text=(
                            "Selected collaboration invitationGroupId "
                            "snapshot"
                        ),
                        max_length=128,
                    ),
                ),
                ("confirm_send_greeting", models.BooleanField(default=False)),
                ("confirm_send_invitation", models.BooleanField(default=False)),
                ("confirm_send_card", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "已完成"),
                            ("PARTIAL_SUCCESS", "部分完成"),
                            ("FAILED", "失败"),
                            ("CANCELLED", "已取消"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                (
                    "model_name",
                    models.CharField(
                        default="deepseek/deepseek-v4-flash",
                        max_length=100,
                    ),
                ),
                (
                    "opencode_session_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("final_summary", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creator_contact_tasks",
                        to="tasks.product",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CreatorContactTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "creator_handle_snapshot",
                    models.CharField(max_length=160),
                ),
                (
                    "normalized_handle",
                    models.CharField(db_index=True, max_length=160),
                ),
                (
                    "nickname_snapshot",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "recent_30_day_revenue_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=22,
                        null=True,
                    ),
                ),
                (
                    "recent_7_day_revenue_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=22,
                        null=True,
                    ),
                ),
                (
                    "chat_creator_id",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "actual_invitation_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "invitation_group_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "已完成"),
                            ("FAILED", "失败"),
                            ("SKIPPED", "已跳过"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("current_step", models.CharField(blank=True, max_length=200)),
                ("message_sent", models.BooleanField(default=False)),
                ("invitation_created", models.BooleanField(default=False)),
                ("card_sent", models.BooleanField(default=False)),
                (
                    "target_plan_message_verified",
                    models.BooleanField(default=False),
                ),
                ("final_send_verified", models.BooleanField(default=False)),
                (
                    "opencode_session_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_targets",
                        to="tasks.relatedcreator",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="creator_contact.creatorcontacttask",
                    ),
                ),
            ],
            options={"ordering": ["rank"]},
        ),
        migrations.CreateModel(
            name="ContactedCreator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(db_index=True, max_length=80)),
                ("normalized_handle", models.CharField(max_length=160)),
                ("creator_handle", models.CharField(max_length=160)),
                (
                    "chat_creator_id",
                    models.CharField(blank=True, max_length=40),
                ),
                ("greeting_sha256", models.CharField(max_length=64)),
                ("invitation_id", models.CharField(max_length=128)),
                ("invitation_name", models.CharField(max_length=255)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("contacted_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successful_contacts",
                        to="tasks.relatedcreator",
                    ),
                ),
                (
                    "contact_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacted_creator_records",
                        to="creator_contact.creatorcontacttask",
                    ),
                ),
            ],
            options={"ordering": ["-contacted_at"]},
        ),
        migrations.CreateModel(
            name="CreatorContactTaskStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_id", models.CharField(max_length=200)),
                ("sequence", models.PositiveIntegerField()),
                ("operation", models.CharField(max_length=160)),
                ("label", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                        ],
                        max_length=16,
                    ),
                ),
                ("input_summary", models.JSONField(blank=True, default=dict)),
                ("output_summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="creator_contact.creatorcontacttarget",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="creator_contact.creatorcontacttask",
                    ),
                ),
            ],
            options={"ordering": ["sequence"]},
        ),
        migrations.CreateModel(
            name="DirectedCollaborationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(db_index=True, max_length=80)),
                (
                    "external_invitation_id",
                    models.CharField(
                        help_text="TikTok invitationGroupId",
                        max_length=128,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "进行中"),
                            ("EXPIRING", "即将到期"),
                            ("CANCELLED", "取消中"),
                            ("COMPLETED", "已完成"),
                            ("UNKNOWN", "未知"),
                        ],
                        db_index=True,
                        default="ONGOING",
                        max_length=32,
                    ),
                ),
                ("product_count", models.PositiveIntegerField(default=0)),
                (
                    "invited_creator_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "accepted_creator_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "promoted_creator_count",
                    models.PositiveIntegerField(default=0),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "external_invitation_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store_id", "external_invitation_id"),
                        name="unique_store_directed_invitation",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="creatorcontacttask",
            name="collaboration_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_tasks",
                to="creator_contact.directedcollaborationoption",
            ),
        ),
        migrations.CreateModel(
            name="GreetingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("content", models.TextField(max_length=2000)),
                (
                    "content_sha256",
                    models.CharField(editable=False, max_length=64),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "-updated_at", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="unique_default_creator_greeting",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="creatorcontacttask",
            name="greeting_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_tasks",
                to="creator_contact.greetingtemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcontacttarget",
            constraint=models.UniqueConstraint(
                fields=("task", "normalized_handle"),
                name="unique_contact_task_creator_handle",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcontacttarget",
            constraint=models.UniqueConstraint(
                fields=("task", "rank"),
                name="unique_contact_task_creator_rank",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactedcreator",
            constraint=models.UniqueConstraint(
                fields=("store_id", "normalized_handle"),
                name="unique_contacted_creator_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="creatorcontacttaskstep",
            constraint=models.UniqueConstraint(
                fields=("task", "step_id"),
                name="unique_creator_contact_task_step",
            ),
        ),
    ]
