# Generated by Django 5.2.16 on 2026-08-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_contact', '0011_contact_active_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorcontacttask',
            name='model_name',
            field=models.CharField(default='deepseek/deepseek-v4-flash', max_length=100),
        ),
    ]
