# Generated by Django 5.2.16 on 2026-07-29 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_key', models.CharField(max_length=400, unique=True)),
                ('creator_handle_snapshot', models.CharField(blank=True, max_length=160)),
                ('creator_name_snapshot', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=320)),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENDING', '发送中'), ('SENT', '发送成功'), ('FAILED', '发送失败'), ('SKIPPED', '已跳过')], db_index=True, default='PENDING', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='tasks.relatedcreator')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
